language: generic 
sudo: required
services: 
    - docker 

before_install:
    - docker build -t claudiocoder/react-app-with-docker -f Dockerfile.dev .

script:
    - docker run -e CI=true claudiocoder/react-app-with-docker npm run test -- --coverage

# deploy: 
#     edge: true
#     provider: elasticbeanstalk
#     region: "us-west-2"   
#     app: name-of-the-app-aws
#     env: "Docker-env"
#     bucket_name: "Amazon S3"
#     bucket_path: "docker"
#     on:
#         branch: master
#         access_key_id: $AWS_ACCESS_KEY
#         secret_access_key: $AWS_SECRET_KEY