language: generic 
sudo: required
services: 
    - docker 

before_install:
    - docker build -t claudiocoder/react-app-with-docker -f Dockerfile.dev .

script:
    - docker run -e CI=true claudiocoder/react-app-with-docker npm run test -- --coverage